# Generated by Django 5.2.4 on 2025-07-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.TextField(verbose_name='cuenta')),
                ('codigo', models.IntegerField(verbose_name='codigo')),
            ],
        ),
    ]
