# Generated by Django 5.2.4 on 2025-07-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(verbose_name='nombre')),
                ('precio', models.IntegerField(verbose_name='precio')),
            ],
        ),
    ]
