# Generated by Django 5.2.4 on 2025-07-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.TextField(verbose_name='banco')),
                ('valor', models.IntegerField(verbose_name='valor')),
            ],
        ),
    ]
